import type { StandingsTableRow, StandingsTeam } from './types'

/** Test and Storybook data — the 2026 BCV T20 Regionalliga top four. */
const team = (id: number, shortName: string, isClubTeam = false): StandingsTeam => ({
  id,
  name: isClubTeam ? 'Erlangen Cricket Club I' : shortName,
  shortName,
  isClubTeam,
})

export const STANDINGS_ROWS: StandingsTableRow[] = [
  {
    position: 1,
    team: team(1, 'TSVGC'),
    played: 14,
    won: 10,
    lost: 4,
    tied: 0,
    noResult: 0,
    points: 80,
    winRate: 71.43,
    netRunRate: 1.426,
    runsFor: 2185,
    oversFaced: '243.4',
    runsAgainst: 2016,
    oversBowled: '267.2',
  },
  {
    position: 2,
    team: team(2, 'ECC-I', true),
    played: 14,
    won: 9,
    lost: 3,
    tied: 2,
    noResult: 0,
    points: 80,
    winRate: 71.43,
    netRunRate: 1.1694,
    runsFor: 1954,
    oversFaced: '243.4',
    runsAgainst: 1596,
    oversBowled: '233',
  },
  {
    position: 3,
    team: team(3, 'SDTCC-I'),
    played: 14,
    won: 9,
    lost: 4,
    tied: 1,
    noResult: 0,
    points: 76,
    winRate: 67.86,
    netRunRate: 0.2675,
    runsFor: 1969,
    oversFaced: '245.2',
    runsAgainst: 1937,
    oversBowled: '249.4',
  },
  {
    position: 4,
    team: team(4, 'NCC-I'),
    played: 14,
    won: 9,
    lost: 5,
    tied: 0,
    noResult: 0,
    points: 72,
    winRate: 64.29,
    netRunRate: 1.4985,
    runsFor: 1803,
    oversFaced: '206.5',
    runsAgainst: 1469,
    oversBowled: '203.3',
  },
]
