/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    fixtures: Fixture;
    teams: Team;
    players: Player;
    competitions: Competition;
    media: Media;
    documents: Document;
    'contact-messages': ContactMessage;
    sponsors: Sponsor;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    fixtures: FixturesSelect<false> | FixturesSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    membership: Membership;
    contact: Contact;
    instagram: Instagram;
    journey: Journey;
    impressum: Impressum;
    'privacy-policy': PrivacyPolicy;
  };
  globalsSelect: {
    membership: MembershipSelect<false> | MembershipSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    instagram: InstagramSelect<false> | InstagramSelect<true>;
    journey: JourneySelect<false> | JourneySelect<true>;
    impressum: ImpressumSelect<false> | ImpressumSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * One or two sentences for news cards, search results and link previews.
   */
  excerpt: string;
  /**
   * Shown after the heading and in link previews, e.g. a sponsor logo or the best photo.
   */
  featuredImage?: (number | null) | Media;
  featuredImageStyle: 'photo' | 'logo';
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * More photos, shown as a gallery below the article.
   */
  gallery?: (number | Media)[] | null;
  publishedAt: string;
  /**
   * URL segment, generated from the title if left empty.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for people who cannot see it (required for accessibility).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Matches and results. List teams in batting order for completed matches — winner and margin are calculated from the innings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixtures".
 */
export interface Fixture {
  id: number;
  /**
   * Generated from date and teams.
   */
  title?: string | null;
  competition: number | Competition;
  stage: 'league' | 'qualifier' | 'semi-final' | 'final';
  date: string;
  /**
   * Local time, HH:mm (optional).
   */
  startTime?: string | null;
  /**
   * Ground name (optional).
   */
  venue?: string | null;
  team1: number | Team;
  team2: number | Team;
  status: 'scheduled' | 'completed' | 'abandoned' | 'cancelled';
  /**
   * In batting order.
   */
  innings?:
    | {
        battingTeam: number | Team;
        runs: number;
        wickets: number;
        overs: string;
        /**
         * Allotted overs (reduced if shortened).
         */
        maxOvers: number;
        id?: string | null;
      }[]
    | null;
  result?: {
    method: 'normal' | 'dls' | 'forfeit' | 'walkover' | 'no-result';
    /**
     * For DLS: leave empty if the match was tied.
     */
    winner?: (number | null) | Team;
    marginValue?: number | null;
    marginUnit?: ('runs' | 'wickets') | null;
  };
  /**
   * Set by data imports to avoid duplicates.
   */
  importKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: number;
  /**
   * e.g. "BCV T20 Regionalliga Bayern".
   */
  name: string;
  /**
   * e.g. "2026".
   */
  season: string;
  /**
   * Scheduled overs per innings (20 for T20).
   */
  maxOvers: number;
  /**
   * The home page counts down to the next match of the ticked competitions only.
   */
  isFeatured?: boolean | null;
  /**
   * The league table exactly as published on CricClubs, one row per team in published order (row 1 = position 1).
   */
  standings?:
    | {
        team: number | Team;
        played: number;
        won: number;
        lost: number;
        noResult: number;
        tied: number;
        points: number;
        /**
         * As published, e.g. 71.43.
         */
        winRate: number;
        /**
         * As published, e.g. 1.1694 or -0.2636.
         */
        netRunRate: number;
        runsFor: number;
        oversFaced: string;
        runsAgainst: number;
        oversBowled: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL segment, e.g. "bcv-t20-regionalliga-bayern-2026". Generated if left empty.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  /**
   * Full team name, e.g. "Erlangen Cricket Club I".
   */
  name: string;
  /**
   * Code used by the league, e.g. "ECC-I".
   */
  shortName: string;
  /**
   * Tick for Erlangen Cricket Club teams; results are shown from their perspective.
   */
  isClubTeam?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Only players whose consent is recorded appear on the website. Stats will come from match scorecards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  name: string;
  /**
   * Head-and-shoulders photo, best cut out (transparent PNG or WebP) so the player stands on the club green. Initials are shown without one.
   */
  photo?: (number | null) | Media;
  playingRole?: ('batter' | 'bowler' | 'all-rounder' | 'wicketkeeper') | null;
  battingStyle?: ('right-hand' | 'left-hand') | null;
  bowlingStyle?:
    | (
        | 'right-arm-fast'
        | 'right-arm-medium'
        | 'right-arm-off-spin'
        | 'right-arm-leg-spin'
        | 'left-arm-fast'
        | 'left-arm-medium'
        | 'left-arm-orthodox'
        | 'left-arm-wrist-spin'
      )
    | null;
  /**
   * Club teams the player plays for.
   */
  teams?: (number | Team)[] | null;
  /**
   * Board role, if the player holds one.
   */
  clubOffice?: ('president' | 'vice-president' | 'treasurer' | 'secretary') | null;
  /**
   * Two or three sentences in the player’s own words.
   */
  bio?: string | null;
  /**
   * URL segment, generated from the name if left empty.
   */
  slug: string;
  /**
   * Up to seven players stand in the squad line-up on the home page. Best with a cut-out photo.
   */
  isFeaturedOnHome?: boolean | null;
  /**
   * Name, photo and stats are public only when ticked. On a removal request, untick and delete the photo in Media.
   */
  hasPublishConsent?: boolean | null;
  consentNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Shown as the download link text, e.g. "Membership application form".
   */
  title: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Sent from the contact page. Reply by email, then update the status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  topic: 'membership' | 'sponsorship' | 'matches' | 'other';
  message: string;
  /**
   * Language of the website when it was sent.
   */
  locale: 'en' | 'de';
  status: 'new' | 'replied' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * Shown on the sponsors page: title sponsors first, then by how long they support us.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  /**
   * Shown whole on a white panel; transparent PNG or SVG works best.
   */
  logo: number | Media;
  tier: 'title' | 'sponsor';
  since: number;
  /**
   * One or two sentences about the sponsor.
   */
  description: string;
  website?: string | null;
  /**
   * News article announcing the sponsorship, if any.
   */
  announcement?: (number | null) | News;
  /**
   * Untick when the sponsorship ends.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'fixtures';
        value: number | Fixture;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'competitions';
        value: number | Competition;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  featuredImageStyle?: T;
  body?: T;
  gallery?: T;
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixtures_select".
 */
export interface FixturesSelect<T extends boolean = true> {
  title?: T;
  competition?: T;
  stage?: T;
  date?: T;
  startTime?: T;
  venue?: T;
  team1?: T;
  team2?: T;
  status?: T;
  innings?:
    | T
    | {
        battingTeam?: T;
        runs?: T;
        wickets?: T;
        overs?: T;
        maxOvers?: T;
        id?: T;
      };
  result?:
    | T
    | {
        method?: T;
        winner?: T;
        marginValue?: T;
        marginUnit?: T;
      };
  importKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  isClubTeam?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  playingRole?: T;
  battingStyle?: T;
  bowlingStyle?: T;
  teams?: T;
  clubOffice?: T;
  bio?: T;
  slug?: T;
  isFeaturedOnHome?: T;
  hasPublishConsent?: T;
  consentNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  name?: T;
  season?: T;
  maxOvers?: T;
  isFeatured?: T;
  standings?:
    | T
    | {
        team?: T;
        played?: T;
        won?: T;
        lost?: T;
        noResult?: T;
        tied?: T;
        points?: T;
        winRate?: T;
        netRunRate?: T;
        runsFor?: T;
        oversFaced?: T;
        runsAgainst?: T;
        oversBowled?: T;
        id?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  topic?: T;
  message?: T;
  locale?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  tier?: T;
  since?: T;
  description?: T;
  website?: T;
  announcement?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Fees, training times and the application form, as shown on the membership page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership".
 */
export interface Membership {
  id: number;
  /**
   * Shown side by side, in this order.
   */
  fees?:
    | {
        /**
         * e.g. "Active".
         */
        name: string;
        /**
         * One item per line, shown as a checklist.
         */
        includes: string;
        annualFee: number;
        /**
         * Leave empty if there is no reduction.
         */
        reducedFee?: number | null;
        /**
         * Leave empty if none.
         */
        perMatchFee?: number | null;
        /**
         * Marks it as the way to play league cricket.
         */
        isHighlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown below the fees, e.g. reductions on request.
   */
  feesNote?: string | null;
  /**
   * Cancellation and payment terms (small print).
   */
  terms?: string | null;
  /**
   * PDF offered for download on the membership page.
   */
  applicationForm?: (number | null) | Document;
  sessions?:
    | {
        /**
         * e.g. "Training" or "Match days".
         */
        title: string;
        days: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
        /**
         * HH:mm, e.g. 17:30.
         */
        startTime: string;
        /**
         * HH:mm, e.g. 17:30.
         */
        endTime: string;
        /**
         * e.g. "Erlangen Cricket Ground".
         */
        venue: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. where changes and cancellations are announced.
   */
  sessionsNote?: string | null;
  /**
   * Large photo at the top of the page, e.g. the squad.
   */
  heroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shown on the contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  email: string;
  facebookUrl?: string | null;
  instagramUrl?: string | null;
  /**
   * Where we train and play home matches.
   */
  ground: {
    name: string;
    street: string;
    postalCode: string;
    city: string;
    /**
     * e.g. 49.59391 — right-click the pitch in Google Maps to copy it.
     */
    latitude: number;
    /**
     * e.g. 10.97719
     */
    longitude: number;
    /**
     * How to get there by train, bus or on foot.
     */
    directions?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shows the latest Instagram posts on the home page. Needs a Professional (Business or Creator) Instagram account.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram".
 */
export interface Instagram {
  id: number;
  /**
   * Long-lived token from Meta for Developers (Instagram API with Instagram Login, permission instagram_business_basic). Leave empty to hide the posts.
   */
  accessToken?: string | null;
  /**
   * Set by the website when it renews the token (about weekly).
   */
  tokenRefreshedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The club’s story and timeline, shown on the “Our journey” page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey".
 */
export interface Journey {
  id: number;
  /**
   * Up to three short chapters, shown side by side as cards.
   */
  chapters?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown oldest first; the order here does not matter.
   */
  milestones?:
    | {
        year: number;
        title: string;
        text: string;
        image?: (number | null) | Media;
        /**
         * Optional “Read more” link, e.g. "/news/annual-general-meeting-2024-key-takeaways".
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Legal notice (§ 5 DDG): association name, address, board, register court and number, contact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum".
 */
export interface Impressum {
  id: number;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Privacy policy (GDPR): controller, data processed, hosting, rights of data subjects.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership_select".
 */
export interface MembershipSelect<T extends boolean = true> {
  fees?:
    | T
    | {
        name?: T;
        includes?: T;
        annualFee?: T;
        reducedFee?: T;
        perMatchFee?: T;
        isHighlighted?: T;
        id?: T;
      };
  feesNote?: T;
  terms?: T;
  applicationForm?: T;
  sessions?:
    | T
    | {
        title?: T;
        days?: T;
        startTime?: T;
        endTime?: T;
        venue?: T;
        id?: T;
      };
  sessionsNote?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  email?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  ground?:
    | T
    | {
        name?: T;
        street?: T;
        postalCode?: T;
        city?: T;
        latitude?: T;
        longitude?: T;
        directions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram_select".
 */
export interface InstagramSelect<T extends boolean = true> {
  accessToken?: T;
  tokenRefreshedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey_select".
 */
export interface JourneySelect<T extends boolean = true> {
  chapters?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  milestones?:
    | T
    | {
        year?: T;
        title?: T;
        text?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum_select".
 */
export interface ImpressumSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}